### ISSUE TITLE
work on more than strings

### ISSUE THREAD

**Issue by tamird** [jgautheron/goconst#1]
This would be useful in [cockroachdb/cockroach](https://github.com/cockroachdb/cockroach) if it could also detect duplicate integers. In particular, we want to use constants for `time.Duration`s in our tests - it'd be nice if this tool provided that check.

**Comment by jgautheron** [comment]
You can now use `-numbers`. It searches for duplicate integers and floats.

**Comment by tamird** [comment]
Heh, this is sadly too much of a blunt instrument - it picks up very small numbers that aren't worth extracting like `if len(args) == 1 {....}`. Perhaps a threshold?

**Comment by jgautheron** [comment]
Just implemented `-min` and `-max`, let me know if that helps.
