### ISSUE TITLE
More options for golangci-lint

### ISSUE THREAD

**Issue by Antonboom** [jgautheron/goconst#11]
Hello!

I can see that the linter has a rich set of flags:
```
  -ignore            exclude files matching the given regular expression
  -ignore-tests      exclude tests from the search (default: true)
  -min-occurrences   report from how many occurrences (default: 2)
  -min-length        only report strings with the minimum given length (default: 3)
  -match-constant    look for existing constants matching the values
  -numbers           search also for duplicated numbers
```

but only a couple of options are available [here](https://golangci-lint.run/usage/configuration/)
```
goconst:
    min-len: 3
    min-occurrences: 3
```

It would be very useful for us to ignore some constants, or turn off this linter for tests without touching other linters

Could you help with that? Thanks

**Comment by jgautheron** [comment]
Hi,
The flag must be exposed in golangci-lint, also probably the vendored version in the project is outdated.
There's not much I can do on my side, I'd recommend creating an issue or better even a PR, in the golangci-lint repository.

**Comment by Antonboom** [comment]
@jgautheron, please, look at https://github.com/golangci/golangci-lint/issues/1495#issuecomment-723488256

Can we add the missing API to ditch the `golangci-lint/goconst` fork entirely?

if necessary, we can just open the PR from the fork :)

**Comment by jgautheron** [comment]
@Antonboom this should do it: https://github.com/jgautheron/goconst/commit/ce0d7c014a65a9555788fbfb8ee5086ad9885ccd

**Comment by Antonboom** [comment]
@jgautheron, thank u!

With your permission, I left a couple of comments on the commit above.

**Comment by jgautheron** [comment]
Good catch @Antonboom, updated: https://github.com/jgautheron/goconst/commit/b58d7cf68fc68b9ce6a932bb4f5e48f0a26f19d6
Thanks!
