### ISSUE TITLE
the releases should have `v` prefix

### ISSUE THREAD

**Issue by SVilgelm** [jgautheron/goconst#16]
Hi,
Could you please re-tag (at least latest) releases by adding `v` prefix to each release?
Seems `go get` does not recognize the tags without `v` as versions.

`golangci-lint` uses `github.com/jgautheron/goconst v0.0.0-20201117150253-ccae5bf973f3` in `go.mod` file, and I tried to update it to use the latest version and expected to see `github.com/jgautheron/goconst v1.4.0`, but no changes.
Then I found this issue: https://github.com/golang/go/issues/30146
Seems the `v` is a convention

**Comment by jgautheron** [comment]
I just tagged the last version v1.4.0.
