### ISSUE TITLE
Regression related to #21

### ISSUE THREAD

**Issue by ldez** [jgautheron/goconst#25]
Hello,

It feels like there is a regression related to https://github.com/jgautheron/goconst/pull/21

Inside golangci-lint we use the configuration field `ExcludeTypes`:
https://github.com/golangci/golangci-lint/blob/11bf3d674ab53e8ea4553b5408951293ef6ed314/pkg/golinters/goconst.go#L67-L69

More information: https://github.com/golangci/golangci-lint/issues/4240

ping @phith0n

**Comment by phith0n** [comment]
Yea, thanks @ldez 

I forget to raise the issue.
