### ISSUE TITLE
Constant is not finding

### ISSUE THREAD

**Issue by sonishailendra** [jgautheron/goconst#6]
I have following file,  but when I run `goconst -min-occurrences 1 -output text .` , it does not return anything. As you can see in the code `"http://"` string has two occurrence, my expectation is that `goconst` will show some error but it does not display anything. Am I doing right?

```
package main
import "strings"

var url string

func getUrl() {
	if strings.HasPrefix(url,"http://"){
		url = strings.TrimPrefix(url,"http://")
	} //esle do not control
	url = strings.TrimPrefix(string(url),"/")
}
```

**Comment by jgautheron** [comment]
Hi @sonishailendra my latest commit (https://github.com/jgautheron/goconst/commit/cda7ea3bf591db274392c3619cd82f83bb4f6fbb) takes this case into account.
