### ISSUE TITLE
Don't count backticks as string members

### ISSUE THREAD

**Issue by mwat56** [jgautheron/goconst#7]
goconst -min-length 3  ./...
    goconst -min-length 4  ./...

return both e.g.

    pagehandler.go:807:7:2 other occurrence(s) of "`xt`" found in: pagehandler.go:594:18 pagehandler.go:946:14

and 

    goconst -min-length 5  ./..

doesn't find anything (which is what I expect).
Obviously the backticks in the first two calls are counted as string-members – which they are _not_.

This is because #2 only expects `"` as string delimiter but not backticks and apostrophe.

**Comment by jgautheron** [comment]
Hi @mwat56, I fixed that in my latest commit (https://github.com/jgautheron/goconst/commit/cda7ea3bf591db274392c3619cd82f83bb4f6fbb)
